"""Create a repository to hold ZLS toolchain targets."""

DOC = """\
Create a repository that defines toolchain targets for all ZLS toolchains.

Each generated toolchain is selected by both execution platform constraints and
the Zig SDK version selected through @zig_toolchains//:version.
"""

ATTRS = {
    "names": attr.string_list(doc = "The name suffixes to assign to the generated toolchain targets."),
    "labels": attr.string_list(doc = "The labels to the ZLS toolchain implementation targets."),
    "zig_versions": attr.string_list(doc = "The Zig SDK versions that select the corresponding ZLS toolchain targets."),
    "exec_lengths": attr.int_list(doc = "The length of the slice of the `exec_constraints` attribute that corresponds to each toolchain target."),
    "exec_constraints": attr.string_list(doc = "All toolchain execution platform constraints concatenated to a single list."),
}

def sanitize_version(version):
    """Replace illegal repository name characters in a version string."""
    return version.replace("+", "_P")

def _calc_counter_digits(num):
    return max(4, len(repr(num)))

def _counter_prefix(count, *, width):
    count_repr = repr(count)
    prefix = "0" * (width - len(count_repr))
    return prefix + count_repr

def _toolchains_repo_impl(repository_ctx):
    len_expected = len(repository_ctx.attr.names)
    len_equal = all([
        len_expected == len(getattr(repository_ctx.attr, attr))
        for attr in ["labels", "zig_versions", "exec_lengths"]
    ])
    if not len_equal:
        fail("Lengths of the attributes `names`, `labels`, `zig_versions`, `exec_lengths` must match.")

    len_exec_constraints = 0
    for exec_len in repository_ctx.attr.exec_lengths:
        len_exec_constraints += exec_len

    if not len_exec_constraints == len(repository_ctx.attr.exec_constraints):
        fail("Length of the `exec_constraints` attribute must match the sum of `exec_lengths`.")

    build_content = """\
# Generated by zig/zls/private/repo/toolchains_repo.bzl
#
# These can be registered in the workspace file or passed to --extra_toolchains.
"""

    counter_digits = _calc_counter_digits(len(repository_ctx.attr.zig_versions))
    zipped = zip(
        repository_ctx.attr.names,
        repository_ctx.attr.labels,
        repository_ctx.attr.zig_versions,
        repository_ctx.attr.exec_lengths,
    )
    exec_offset = 0
    for counter, (name, label, zig_version, exec_len) in enumerate(zipped):
        compatible_with = repository_ctx.attr.exec_constraints[exec_offset:exec_offset + exec_len]
        exec_offset += exec_len
        build_content += """
toolchain(
    name = "{prefix}_{name}_toolchain",
    exec_compatible_with = {compatible_with},
    target_settings = ["@zig_toolchains//:{zig_version}"],
    toolchain = "{label}",
    toolchain_type = "@rules_zig//zig/zls:toolchain_type",
)
""".format(
            prefix = _counter_prefix(counter, width = counter_digits),
            name = name,
            compatible_with = compatible_with,
            zig_version = zig_version,
            label = label,
        )

    repository_ctx.file("BUILD.bazel", build_content)

toolchains_repo = repository_rule(
    _toolchains_repo_impl,
    doc = DOC,
    attrs = ATTRS,
)
