"""Implementation of the `zls_repository` repository rule."""

load("@bazel_tools//tools/build_defs/repo:utils.bzl", "update_attrs")

DOC = "Fetch and install a ZLS toolchain."

ATTRS = {
    "url": attr.string(mandatory = True, doc = "The URL to the ZLS release archive."),
    "mirrors": attr.string_list(mandatory = True, doc = "List of URLs to ZLS release mirrors."),
    "sha256": attr.string(mandatory = False, doc = "The expected SHA-256 of the downloaded artifact. Provide only one of `sha256` or `integrity`."),
    "integrity": attr.string(mandatory = False, doc = "The expected checksum of the downloaded artifact in Subresource Integrity format. Provide only one of `sha256` or `integrity`."),
    "zls_version": attr.string(mandatory = True, doc = "The ZLS version number."),
    "platform": attr.string(mandatory = True, doc = "The platform that ZLS can execute on, e.g. `x86_64-linux` or `aarch64-macos`."),
}

def _basename(path):
    return path.rpartition("/")[-1]

def _mirrors_urls(url, mirrors):
    filename = _basename(url)
    return [
        mirror + "/" + filename
        for mirror in mirrors
    ] + [url]

def _get_integrity_args(*, sha256, integrity):
    result = {}

    if sha256 and integrity:
        fail("You may only specify one of `sha256` or `integrity`.")
    elif sha256:
        result["sha256"] = sha256
    elif integrity:
        result["integrity"] = integrity

    return result

def _zls_repository_impl(repository_ctx):
    bin = "zls.exe" if repository_ctx.attr.platform.find("windows") != -1 else "zls"

    repository_ctx.file("BUILD.bazel", """\
# Generated by zig/zls/private/repo/zls_repository.bzl

load("@rules_zig//zig/zls:toolchain.bzl", "zls_toolchain")

zls_toolchain(
    name = "zls_toolchain",
    bin = {bin},
    zls_version = {zls_version},
)
""".format(
        bin = repr(bin),
        zls_version = repr(repository_ctx.attr.zls_version),
    ))

    download_args = {
        "url": _mirrors_urls(
            url = repository_ctx.attr.url,
            mirrors = repository_ctx.attr.mirrors,
        ),
    }
    integrity = _get_integrity_args(
        sha256 = repository_ctx.attr.sha256,
        integrity = repository_ctx.attr.integrity,
    )
    download_args.update(**integrity)

    download = repository_ctx.download_and_extract(**download_args)

    integrity_override = {} if integrity else {"integrity": download.integrity}

    return update_attrs(repository_ctx.attr, ATTRS.keys(), integrity_override)

zls_repository = repository_rule(
    _zls_repository_impl,
    attrs = ATTRS,
    doc = DOC,
)
