load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "zig_repository",
    srcs = ["zig_repository.bzl"],
    visibility = ["//zig:__subpackages__"],
    deps = [
        "//zig/private/common:zig_cache",
        "@bazel_tools//tools/build_defs/repo:utils.bzl",
    ],
)

bzl_library(
    name = "toolchains_repo",
    srcs = ["toolchains_repo.bzl"],
    visibility = ["//zig:__subpackages__"],
    deps = [
        "//zig/private/common:semver",
        "@bazel_skylib//lib:sets",
    ],
)

bzl_library(
    name = "zig_host_toolchain",
    srcs = ["zig_host_toolchain.bzl"],
    visibility = ["//zig:__subpackages__"],
    deps = ["@zig_toolchains//private:toolchains"],
)

bzl_library(
    name = "zig_package",
    srcs = ["zig_package.bzl"],
    visibility = ["//zig:__subpackages__"],
    deps = ["@rules_zig_host_toolchain//:toolchain"],
)

bzl_library(
    name = "zig_deps_hub",
    srcs = ["zig_deps_hub.bzl"],
    visibility = ["//zig:__subpackages__"],
    deps = ["@bazel_skylib//lib:paths"],
)

# Execute `bazel run //util:update_filegroups` to update this target.
filegroup(
    name = "all_files",
    srcs = [
        ":BUILD.bazel",
        ":toolchains_repo.bzl",
        ":zig_deps_hub.bzl",
        ":zig_host_toolchain.bzl",
        ":zig_package.bzl",
        ":zig_repository.bzl",
    ],
    visibility = ["//zig/private:__pkg__"],
)
