"""Implementation of the `zig_deps` hub repository rule."""

DOC = """\
The `@zig_deps` hub repository.

Exposes each manifest's direct Zig dependencies by name, grouped under the
manifest's own Bazel package and scoped to that package's subtree. Generated by
the `zig_packages` module extension.
"""

ATTRS = {
    "manifests": attr.string(
        mandatory = True,
        doc = "JSON-encoded list of `{package, scope, deps}` manifest entries.",
    ),
    "packages": attr.string_keyed_label_dict(
        mandatory = True,
        doc = "Map from each package key to its `files` target.",
    ),
}

_ALIAS = """\
alias(
    name = "{name}",
    actual = "{actual}",
    visibility = ["{scope}"],
)
"""

def _zig_deps_hub_impl(repository_ctx):
    packages = repository_ctx.attr.packages
    manifests = json.decode(repository_ctx.attr.manifests)

    builds = {}
    for manifest in manifests:
        aliases = [
            _ALIAS.format(name = name, actual = str(packages[key]), scope = manifest["scope"])
            for name, key in manifest["deps"].items()
        ]
        builds[manifest["package"]] = "\n".join(aliases)

    if "" not in builds:
        builds[""] = ""

    for package, content in builds.items():
        path = package + "/BUILD.bazel" if package else "BUILD.bazel"
        repository_ctx.file(path, content)

zig_deps_hub = repository_rule(
    _zig_deps_hub_impl,
    attrs = ATTRS,
    doc = DOC,
)
