"""Implementation of the `zig_deps` hub repository rule."""

DOC = """\
The `@zig_deps` hub repository.

Exposes each manifest's direct Zig dependencies by name, grouped under the
manifest's own Bazel package and scoped to that package's subtree. Generated by
the `zig_packages` module extension.
"""

ATTRS = {
    "manifests": attr.string(
        mandatory = True,
        doc = "JSON-encoded list of `{repo, package, scope, deps}` manifest entries.",
    ),
    "packages": attr.string_keyed_label_dict(
        mandatory = True,
        doc = "Map from each package key to its `files` target.",
    ),
}

_ALIAS = """\
alias(
    name = "{name}",
    actual = "{actual}",
    visibility = ["{scope}"],
)
"""

_DEFS = '''\
"""Accessors for the Zig package dependencies of each `from_file` manifest."""

_MANIFESTS = json.decode("""%MANIFESTS%""")

def zig_dep(name):
    """Return the label of dependency `name` of the enclosing Zig manifest."""
    path, names = _manifest()
    if name not in names:
        fail("Zig manifest '%s' declares no dependency '%s'; available: %s" % (path, name, names))
    return _label(path, name)

def zig_deps():
    """Return the labels of every dependency of the enclosing Zig manifest."""
    path, names = _manifest()
    return [_label(path, name) for name in names]

def _manifest():
    repo = native.repo_name()
    package = native.package_name()
    manifests = _MANIFESTS.get(repo, {})
    manifest = _enclosing(manifests, package)
    if manifest == None:
        fail("no Zig `from_file` manifest covers package '%s'" % package)
    path = "/".join([part for part in [repo, manifest] if part])
    return path, manifests[manifest]

def _label(path, name):
    return Label("//" + path + ":" + name)

def _enclosing(manifests, package):
    candidate = package
    for _ in range(len(package) + 1):
        if candidate in manifests:
            return candidate
        if not candidate:
            break
        candidate = candidate.rpartition("/")[0]
    return None
'''

def _hub_path(manifest):
    return "/".join([part for part in [manifest["repo"], manifest["package"]] if part])

def _zig_deps_hub_impl(repository_ctx):
    packages = repository_ctx.attr.packages
    manifests = json.decode(repository_ctx.attr.manifests)

    builds = {}
    registry = {}
    for manifest in manifests:
        aliases = [
            _ALIAS.format(name = name, actual = str(packages[key]), scope = manifest["scope"])
            for name, key in manifest["deps"].items()
        ]
        builds[_hub_path(manifest)] = "\n".join(aliases)
        registry.setdefault(manifest["repo"], {})[manifest["package"]] = manifest["deps"].keys()

    if "" not in builds:
        builds[""] = ""

    for path, content in builds.items():
        build_file = path + "/BUILD.bazel" if path else "BUILD.bazel"
        repository_ctx.file(build_file, content)

    repository_ctx.file("defs.bzl", _DEFS.replace("%MANIFESTS%", json.encode(registry)))

zig_deps_hub = repository_rule(
    _zig_deps_hub_impl,
    attrs = ATTRS,
    doc = DOC,
)
