"""Implementation of the `zig_deps` hub repository rule."""

load("@bazel_skylib//lib:paths.bzl", "paths")

DOC = """\
The `@zig_deps` hub repository.

Exposes each manifest's direct Zig dependencies by name, grouped under the
manifest's own Bazel package and scoped to that package's subtree. Generated by
the `zig_packages` module extension.
"""

ATTRS = {
    "manifests": attr.string(
        mandatory = True,
        doc = "JSON-encoded list of `{repo, package, scope, deps}` manifest entries.",
    ),
    "packages": attr.string_keyed_label_dict(
        mandatory = True,
        doc = "Map from each package key to its `files` target.",
    ),
}

_ALIAS = """\
alias(
    name = "{name}",
    actual = "{actual}",
    visibility = ["{scope}"],
)
"""

# The generated accessors reference each spoke by its canonical (`@@`) repo name,
# which is resolved at module-extension time and has no apparent-name alias here.
# buildifier: disable=canonical-repository
_DEFS = '''\
"""Accessors for the Zig package dependencies of each `from_file` manifest."""

load("@bazel_skylib//lib:paths.bzl", "paths")

_MANIFESTS = json.decode("""%MANIFESTS%""")

def zig_dep(name, module = None):
    """Return the label of dependency `name` of the enclosing Zig manifest.

    Resolves to the dependency's module of the same name. Pass `module` to select
    a differently named module exposed by the same (URL) dependency.
    """
    path, deps = _manifest()
    if name not in deps:
        fail("Zig manifest '%s' declares no dependency '%s'; available: %s" % (path, name, sorted(deps)))
    if module == None or module == name:
        return _label(path, name)
    dep = deps[name]
    if not dep["select"]:
        fail("Zig dependency '%s' is a path dependency; cannot select module '%s'" % (name, module))
    return Label("@@" + dep["spoke"] + "//:" + module)

def zig_deps():
    """Return the labels of every dependency of the enclosing Zig manifest."""
    path, deps = _manifest()
    return [_label(path, name) for name in deps]

def _manifest():
    repo = native.repo_name()
    package = native.package_name()
    manifests = _MANIFESTS.get(repo, {})
    manifest = _enclosing(manifests, package)
    if manifest == None:
        fail("no Zig `from_file` manifest covers package '%s'" % package)
    parts = [part for part in [repo, manifest] if part]
    path = paths.join(*parts) if parts else ""
    return path, manifests[manifest]

def _label(path, name):
    return Label("//" + path + ":" + name)

def _enclosing(manifests, package):
    candidate = package
    for _ in range(len(package) + 1):
        if candidate in manifests:
            return candidate
        if not candidate:
            break
        candidate = candidate.rpartition("/")[0]
    return None
'''

def _hub_path(manifest):
    # `paths.join` keeps empty trailing segments (e.g. `repo/`), so drop empties
    # first: the main module has no repo prefix and root manifests no package.
    parts = [part for part in [manifest["repo"], manifest["package"]] if part]
    return paths.join(*parts) if parts else ""

def _zig_deps_hub_impl(repository_ctx):
    packages = repository_ctx.attr.packages
    manifests = json.decode(repository_ctx.attr.manifests)

    builds = {}
    registry = {}
    for manifest in manifests:
        aliases = []
        deps = {}
        for name, dep in manifest["deps"].items():
            label = packages[dep["target"]]
            aliases.append(_ALIAS.format(name = name, actual = str(label), scope = manifest["scope"]))

            # URL dependencies expose further modules by name, addressed through
            # their spoke's canonical repository; path dependencies do not.
            deps[name] = {"spoke": label.repo_name if dep["url"] else "", "select": dep["url"]}
        builds[_hub_path(manifest)] = "\n".join(aliases)
        registry.setdefault(manifest["repo"], {})[manifest["package"]] = deps

    if "" not in builds:
        builds[""] = ""

    for path, content in builds.items():
        build_file = path + "/BUILD.bazel" if path else "BUILD.bazel"
        repository_ctx.file(build_file, content)

    repository_ctx.file("defs.bzl", _DEFS.replace("%MANIFESTS%", json.encode(registry)))

zig_deps_hub = repository_rule(
    _zig_deps_hub_impl,
    attrs = ATTRS,
    doc = DOC,
)
