"""Implementation of the `zig_host_toolchain` repository rule."""

load("@zig_toolchains//private:toolchains.bzl", "ZIG_TOOLCHAINS")

DOC = """\
Expose the latest registered Zig SDK for the host platform.

Generates a `toolchain.bzl` file with a `zig_path(ctx)` function that resolves
the host platform's Zig binary from a repository_ctx or module_ctx.
"""

def _detect_host_platform(repository_ctx):
    os_name = repository_ctx.os.name
    arch = repository_ctx.os.arch

    if "linux" in os_name:
        os = "linux"
    elif "mac" in os_name or "darwin" in os_name:
        os = "macos"
    elif "windows" in os_name:
        os = "windows"
    else:
        fail("Unsupported host operating system: {}".format(os_name))

    if arch in ["amd64", "x86_64", "x64"]:
        cpu = "x86_64"
    elif arch in ["aarch64", "arm64"]:
        cpu = "aarch64"
    else:
        fail("Unsupported host CPU architecture: {}".format(arch))

    return "{}-{}".format(cpu, os)

def _zig_host_toolchain_impl(repository_ctx):
    platform = _detect_host_platform(repository_ctx)

    zig = None
    for toolchain in ZIG_TOOLCHAINS:
        if toolchain.exec_platform == platform:
            zig = toolchain.zig
            break

    if zig == None:
        fail("No registered Zig SDK supports the host platform '{}'.".format(platform))

    repository_ctx.file("BUILD.bazel", "")
    repository_ctx.file("toolchain.bzl", """\
# Generated by zig_host_toolchain.bzl

_ZIG = Label({})

def zig_path(ctx):
    return ctx.path(_ZIG)
""".format(repr(str(zig))))

zig_host_toolchain = repository_rule(
    _zig_host_toolchain_impl,
    doc = DOC,
)
