load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")

write_source_files(
    name = "write_bazelversion",
    files = {
        ".bazelversion": "@rules_zig//:.bazelversion",
    },
)
