bazel_dep(name = "rules_zig", version = "0.6.1", dev_dependency = True)
bazel_dep(name = "aspect_bazel_lib", version = "2.22.5", dev_dependency = True)
bazel_dep(name = "bazel_features", version = "1.47.0", dev_dependency = True)
bazel_dep(name = "bazel_skylib", version = "1.9.0", dev_dependency = True)
bazel_dep(name = "platforms", version = "1.1.0", dev_dependency = True)
bazel_dep(name = "rules_cc", version = "0.2.18", dev_dependency = True)

local_path_override(
    module_name = "rules_zig",
    path = "../..",
)

zig = use_extension(
    "@rules_zig//zig:extensions.bzl",
    "zig",
    dev_dependency = True,
)
zig.toolchain(zig_version = "0.16.0")
zig.toolchain(zig_version = "0.15.2")
use_repo(zig, "zig_toolchains")

new_git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")

new_git_repository(
    name = "arocc",
    build_file = "//third_party/arocc:arocc.bazel",
    commit = "5f5a050569a95ecc40a426f0c3666ae7ef987ede",
    remote = "https://github.com/Vexu/arocc.git",
)

new_git_repository(
    name = "translate-c",
    build_file = "//third_party/translate-c:translate-c.bazel",
    commit = "46b5609b5ac4c0a896217d1d984f3ae50e4810b5",
    remote = "https://codeberg.org/ziglang/translate-c",
)

register_toolchains("//third_party/translate-c:toolchain")

bazel_dep(name = "toolchains_buildbuddy", version = "0.0.4", dev_dependency = True)

buildbuddy = use_extension(
    "@toolchains_buildbuddy//:extensions.bzl",
    "buildbuddy",
    dev_dependency = True,
)
use_repo(buildbuddy, "buildbuddy_toolchain")

bazel_dep(name = "runfiles_library_dependency", dev_dependency = True)
local_path_override(
    module_name = "runfiles_library_dependency",
    path = "runfiles-library/dependency",
)

local_path_override(
    module_name = "runfiles_library_transitive_dependency",
    path = "runfiles-library/dependency/transitive-dependency",
)

bazel_dep(
    name = "rules_foreign_cc",
    version = "0.15.1",
    dev_dependency = True,
)
