local_repository(
    name = "rules_zig",
    path = "../../../..",
)

load("@rules_zig//zig:repositories.bzl", "rules_zig_dependencies", "zig_register_toolchains")

rules_zig_dependencies()

load("//:zig_version.bzl", "ZIG_VERSION")

zig_register_toolchains(
    name = "zig",
    zig_version = ZIG_VERSION,
)
