load("@bazel_skylib//rules:diff_test.bzl", "diff_test")
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_zig//zig:defs.bzl", "zig_binary", "zig_c_library", "zig_configure_test", "zig_library")

cc_library(
    name = "local_c",
    srcs = ["local.c"],
    hdrs = ["local.h"],
)

zig_c_library(
    name = "local_zig",
    cdeps = [":local_c"],
)

zig_library(
    name = "module",
    main = "module.zig",
    deps = [":local_zig"],
)

cc_library(
    name = "private_h",
    hdrs = ["private.h"],
)

cc_library(
    name = "global_c",
    srcs = ["global.c"],
    hdrs = ["global.h"],
    deps = [":private_h"],
)

zig_binary(
    name = "binary",
    main = "main.zig",
    deps = [
        ":global_c",
        ":module",
    ],
)

zig_binary(
    name = "global_binary",
    main = "main_global.zig",
    deps = [":global_c"],
)

genrule(
    name = "output",
    outs = ["output.actual"],
    cmd = "$(execpath :binary) > $(OUTS)",
    tools = [":binary"],
)

genrule(
    name = "global_output",
    outs = ["output_global.actual"],
    cmd = "$(execpath :global_binary) > $(OUTS)",
    tools = [":global_binary"],
)

diff_test(
    name = "output_test",
    size = "small",
    file1 = ":output.expected",
    file2 = ":output.actual",
)

diff_test(
    name = "global_output_test",
    size = "small",
    file1 = ":output_global.expected",
    file2 = ":output_global.actual",
)

zig_configure_test(
    name = "output_test_external_translate_c",
    size = "small",
    actual = ":global_output_test",
    target_compatible_with = select({
        "@zig_toolchains//:0.15.2": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    translate_c = 1,
)
