# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3`
# and put the release notes into the commit message for the tag.
name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g. v1.2.3). Must already exist."
        type: string
        required: true

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  tests:
    uses: ./.github/workflows/ci.yaml
    secrets:
      BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}

  release:
    needs: [tests]
    uses: bazel-contrib/.github/.github/workflows/release_ruleset.yaml@v7.4.0
    with:
      release_files: rules_zig-*.tar.gz
      prerelease: ${{ contains(inputs.tag || github.ref_name, '-') }}
      tag_name: ${{ inputs.tag || github.ref_name }}

  publish-to-bcr:
    needs: [release]
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1.2.0
    with:
      tag_name: ${{ inputs.tag || github.ref_name }}
      registry_fork: hermeticbuild/bazel-central-registry
    permissions:
      attestations: write
      contents: write
      id-token: write
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
